version: "3.9"
services:
  expressapp:
    container_name: expressapp
    build: ./backend
    expose:
      - 3000
    volumes:
      - ./backend:/usr/src/app
  nginx:
    build: ./nginx
    ports:
      - 80:80
    links:
      - expressapp
    restart: always
